### ISSUE TITLE
UI: usability improvement.

### ISSUE THREAD

**Issue by jspreddy** [jkhask/passport-app#2]
1. Move the form to the top of the page (Below the title).
2. Make the tree container expand to fit the tree. It is ok of the entire page has a vertical scroll as a result.
![ui_improvements](https://cloud.githubusercontent.com/assets/2302194/25193203/48f71318-2504-11e7-9f5a-0a13aae655ac.jpg)

**Comment by jkhask** [comment]
Great suggestions, I have updated the app accordingly
